
safe: false

markdown: kramdown
highlighter: pygments

exclude: [
  "README.md",
  "LICENSE.md",
  "CNAME",
  ".gitignore",
  "scripts",
  "komiga.sublime-project",
  "komiga.sublime-workspace"
]

## Site configuration

url: http://komiga.com
meta:
  perma-url: http://komiga.com
  title: komiga
  run-years: "2012–2015"
  image: http://lh4.googleusercontent.com/-fek5nINIJug/UMVJdFtlHVI/AAAAAAAAAHw/sb0KGgMaPPU/k-nrm-256.png
  analytics_id: "UA-6565507-1"
  analytics_domain_name: null

## Style

style:
  format:
    ymd: '%d %B %Y'

## Static content

nav-items-predefined: {
  home    : {title: "top"      , url: "#", icon: "komiga.svg", icon-class: "home"},
  backhome: {title: "main page", url: "/", icon: "komiga.svg", icon-class: "home"},
  github  : {title: "GitHub"   , url: "https://github.com/komiga" , icon: "github.svg"},
  twitter : {title: "Twitter"  , url: "https://twitter.com/komiga", icon: "twitter.svg"}
}
